### ISSUE TITLE
ModuleNotFoundError: No module named 'validate.data'; 'validate' is not a package

### ISSUE THREAD

**Issue by caseybasichis** [mutantstandard/build#3]
orxport.py worked, but I'm running into an error on the last step:

`./Forc/forc.py -m manifest/font/manifest.json -a manifest/font/aliases.json -i out/font_sources -o out/fonts -F [formats] --afsc
Traceback (most recent call last):
  File "./Forc/forc.py", line 9, in <module>
    from start import start
  File "/home/caseybasichis/Prog/font/build/Forc/start.py", line 6, in <module>
    from manifest.manifest import checkTransformManifest
  File "/home/caseybasichis/Prog/font/build/Forc/manifest/manifest.py", line 3, in <module>
    from manifest.metadata import checkTransformMetadata
  File "/home/caseybasichis/Prog/font/build/Forc/manifest/metadata.py", line 2, in <module>
    from validate.data import validatePostScriptName
ModuleNotFoundError: No module named 'validate.data'; 'validate' is not a package`

**Comment by caseybasichis** [comment]
I doubt this is the issue, but the filenames were a bit out of sync on the build instructions.  Both orxporter and forc seem to be all lower case.  In the build readme:

`./Orxporter/orxport.py`

and

`./Forc/Forc.py`

**Comment by caseybasichis** [comment]
Tinkering a bit:

changing line 2 of /forc/manifest/metadata.py to look for packages locally 

`from .validate.data import validatePostScriptName`

Move me to this error 

`Traceback (most recent call last):
  File "./Forc/forc.py", line 9, in <module>
    from start import start
  File "/home/caseybasichis/Prog/font/build/Forc/start.py", line 6, in <module>
    from manifest.manifest import checkTransformManifest
  File "/home/caseybasichis/Prog/font/build/Forc/manifest/manifest.py", line 3, in <module>
    from manifest.metadata import checkTransformMetadata
  File "/home/caseybasichis/Prog/font/build/Forc/manifest/metadata.py", line 2, in <module>
    from .validate.data import validatePostScriptName
ModuleNotFoundError: No module named 'manifest.validate'
`
Is there a package install step I'm missing for Forc?

**Comment by dzuk-mutant** [comment]
I'm sorry that I missed this all these years ago. I'm going to assume this is fixed because the codebase has changed since this issue, but feel free to re-open if it's still a thing.

**Comment by Kai-ogg** [comment]
Issue still persists, the fix on my end was renaming the `validate` folder to something else, i.e. `validate_different_name` and updating the imports respectively.
Seems like there's a naming conflict going on somewhere, and Python, being Python, isn't giving any useful information.

Hope this helps anyone else having this issue
